### PR TITLE
Remove loop in favor of math

### PR DESCRIPTION
**Pull request by jgeralnik**
Rather than checking every number until 2**30 to find the seed, we can just calculate it.

### CODE REVIEW

**Comment by ALSchwalm** [comment]
I'm gonna need a little help understanding why this works before I merge. In general, I can see that given that `value[1]` is just `(value[0] * 3 + seed2) % 0x3FFFFFFF`, it seems reasonable that `seed2` should just be something like `seed2 = (seed1 * 3 - value[1]) % 0x3FFFFFFF`. I don't see why that value is being subtracted from `0x3FFFFFFF`. I assume this has something to do with the modulus, but I'm not sure why it works.

**Comment by jgeralnik** [comment]
On second thought my calculation is a little silly and python is friendlier than I thought. Here's my thought process, but I'll send a correct commit shortly:

You're missing a minus sign from your calculations:
(Equations are mod 0x3FFFFFFF)

value[1] = 3*seed1 + seed2
seed2 = value[1] - 3*seed1

Apparently I wasn't thinking so much when I made the commit, so I decided the logical equation was:

seed2 = -(3*seed1 - value[1])

In most programming

**Comment by jgeralnik** [comment]
OK, I'm on mobile and accidentally pressed buttons so I'm going to stop for now and try again once I get to my computer :-). Ignore the previous message for now

**Comment by jgeralnik** [comment]
Sorry about the closing opening thing, that's what happens when you try to comment on issues on mobile.

On second thought my calculation is a little silly and python is friendlier than I thought. Here's my thought process, but I'll send a correct commit shortly.

You're missing a minus sign from your calculations:
(Equations are mod 0x3FFFFFFF)

```
value[1] = 3*seed1 + seed2
seed2 = value[1] - 3*seed1
```

Apparently I wasn't thinking so much when I made the commit, so I decided the logical equation was:

```
seed2 = -(3*seed1 - value[1])
```

In most programming languages, negative numbers modulo give negative results, so for example

```
-8 % 5 = -3
```

I thought python also worked this way, and negative numbers are undesirable, so my thought was that by adding 0x3FFFFFFF we can get around negative numbers.

```
seed2 = -(3*seed1 - value[1]) = 0x3FFFFFFF - (3*seed1 - value[1])
```

(because all calculations are mod 0x3FFFFFFF and 0x3FFFFFFF = 0 mod 0x3FFFFFFF).

However, this is silly for two few reasons. First, there is no guarantee that (3 * seed1 - value[1]) is negative, so really we need an additional modulo at the end:

```
(0x3FFFFFFF - (3*seed1 - value[1]) % 0x3FFFFFFF) % 0x3FFFFFFF
```

in order to ensure 0 <= seed2 < 0x3FFFFFFF. But secondly, python actually deals with negative numbers the "correct" (in my opinion) way, such that negative numbers modulo positive numbers always return positive numbers. That is:

```
-8 % 5 = 2
```

So, going back to our original calculation, we can just use:

```
seed2 = (value[1] - 3*seed1) % 0x3FFFFFFF
```

and be done with it.

I'll send a new commit in the next few minutes

**Comment by jgeralnik** [comment]
There we go. Better now?

**Comment by ALSchwalm** [comment]
This makes a lot more sense to me. Merging.

Thanks for the PR and explanation!

**Pull request merged**
